name: HeliPartsTracker
options:
  bundleIdPrefix: com.helitracker
targets:
  HeliPartsTracker:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: [HeliPartsTracker]
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.helitracker.HeliPartsTracker
      DEVELOPMENT_TEAM: 7KZX225WZP
